version: "3.5"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.node
      args:
        PACKAGE_PATH: ./api
        WORKING_DIR: /src/api
    expose:
      - 4000
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=development
    env_file:
      - ./dev.env
    volumes:
      - .:/src
    depends_on:
      - postgres
    command: ["yarn", "start"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.node
      args:
        PACKAGE_PATH: ./frontend
        WORKING_DIR: /src/frontend
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      - REACT_APP_ENV=development
      - HTTPS=true
      - NODE_PATH=/src/frontend/src
    volumes:
      - .:/src
    command: ["yarn", "start"]

  postgres:
    image: postgres
    restart: always
    env_file: ./dev.env
    ports:
      - 8080:8080
