FROM node:8.12.0

ARG PACKAGE_PATH=
ARG WORKING_DIR=/src

WORKDIR $WORKING_DIR

COPY $PACKAGE_PATH/package.json $WORKING_DIR/package.json
COPY $PACKAGE_PATH/yarn.lock $WORKING_DIR/yarn.lock
RUN npm install

COPY . /src

VOLUME $WORKING_DIR/node_modules

CMD [ "npm", "start" ]